services:
  db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data

  odoo16:
    image: odoo:16.0
    depends_on:
      - db
    ports:
      - "8068:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
    command: odoo -d odoo_db -u hustle_website --dev=xml --db_user=odoo --db_password=odoo --db_host=db

volumes:
  odoo-web-data:
  odoo-db-data:
  odoo-web-data2: